### ISSUE TITLE
QC_Tools compliation error

### ISSUE THREAD

**Issue by pradeepvaradwaj** [JoshuaSBrown/QC_Tools#24]
I am not a superuser. So, I tried to use: make install install-root=, with no success. Any help!

-- Install configuration: ""
-- Installing: /usr/local/bin/calc_J
CMake Error at cmake_install.cmake:42 (FILE):
  file INSTALL cannot copy file
  "/home/xxx/QC_Tools-master/build/calc_J" to
  "/usr/local/bin/calc_J".

make: *** [Makefile:66: install] Error 1

**Comment by JoshuaSBrown** [comment]
You can use the executable calc_J directly from the build directly. Or you could simply move it to you local bin. How familiar are you with Linux?

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 26, 2018 at 4:38 AM, pradeepvaradwaj<notifications@github.com> wrote:   
I am not a superuser. So, I tried to use: make install install-root=, with no success. Any help!

-- Install configuration: ""
-- Installing: /usr/local/bin/calc_J
CMake Error at cmake_install.cmake:42 (FILE):
file INSTALL cannot copy file
"/home/xxx/QC_Tools-master/build/calc_J" to
"/usr/local/bin/calc_J".

make: *** [Makefile:66: install] Error 1

**Comment by JoshuaSBrown** [comment]
@pradeepvaradwaj I have updated the wiki. Let me know if this clarifies things. 

https://github.com/JoshuaSBrown/QC_Tools/wiki/3.-Compiling
