### ISSUE TITLE
ERROR Matrix_Multiply only allowed for nxm by lxn matrices       second matrix must have same number of colums as first       matrix has number of rows

### ISSUE THREAD

**Issue by khatiaxomiya** [JoshuaSBrown/QC_Tools#48]
kalyan@kalyan-Inspiron-3558:~/Computational/QC_Tools-master$ calc_J -p_1 GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-P.pun -orb_ty_1 HOMO -p_2 GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-m4.pun -orb_ty_2 LUMO -p_P GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-4.pun

Running calc_J VERSION 1.5
log file for first monomer is:      GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-P.log
log file for second monomer is:     GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-m4.log
log file for dimer is:              GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-4.log
pun file for the first monomer is:  GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-P.pun
pun file for the second monomer is: GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-m4.pun
pun file for the dimer is:          GAUSSIANFILES/TI-6/ol5b02417_si_006_TI-4.pun

Dimer     Spin Alpha
Monomer 1 Spin Alpha Orbital HOMO
Monomer 2 Spin Alpha Orbital LUMO
ERROR Matrix_Multiply only allowed for nxm by lxn matrices
      second matrix must have same number of colums as first
      matrix has number of rows

**Comment by JoshuaSBrown** [comment]
Can you send me the input files so I can try to reproduce the error?

**Comment by JoshuaSBrown** [comment]
They don't have to be the exact same files I just need to be able to reproduce the error.

**Comment by JoshuaSBrown** [comment]
https://github.com/JoshuaSBrown/QC_Tools/pull/49 Fixed thanks to files provided by Caleb Wehrmann.
