### ISSUE TITLE
it seems that it can't work very well when basis set is very large

### ISSUE THREAD

**Issue by ivorever** [JoshuaSBrown/QC_Tools#6]
I am calculating a system including a dimer with 100 atoms and 500+ electrons on the b3lyp/6-31g(d,p) calculation level. when doing calc-J calculation, it went wrong.
the error information is followed:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
Aborted (core dumped)

**Comment by JoshuaSBrown** [comment]
Thanks for opening the issue. It would also be useful to get a copy of the file it failed on.

**Comment by ivorever** [comment]
The output files are very large. I will upload the input files.
It works when  I remove the p behind the # and pop=full
I have not test whether the #p or pop=full make the program fail.

[11.txt](https://github.com/JoshuaSBrown/QC_Tools/files/2066860/11.txt)
[12.txt](https://github.com/JoshuaSBrown/QC_Tools/files/2066861/12.txt)
[13.txt](https://github.com/JoshuaSBrown/QC_Tools/files/2066862/13.txt)

**Comment by ivorever** [comment]
It fails when I add pop=full to the Gaussian input files

**Comment by JoshuaSBrown** [comment]
Ah I imagine that this is a result of using #p as this will output additional information in the output file and may mess up the file parsing. For now as a temporary fix simply omit the #p. I will see if I can find why this occurring.

**Comment by dwaipayanroni** [comment]
Hi ivorever,
I faced the same prob as you, but after removing the 'p' in the route section it is working. But I am facing a new problem now, the matrix multiplication is not happening due to the diff in the number of MOs and NBasis. 
Can you please tell me that what was your no of MOs and NBasis for monomer and dimer, were they different or same? My molecule is also as large as yours.

**Comment by JoshuaSBrown** [comment]
If you run with the pop=full keyword all of the MOs should be printed let me know if this works. 

http://gaussian.com/population/

**Comment by JoshuaSBrown** [comment]
Ok, I will have to actually run your simulation and figure out what exactly is going on. For now what you can do is cut the molecule up, typically the transfer integrals is only strongly dependent on the closest atoms between molecules so if you remove the ones that are far away from the interaction you should be able to get a fairly accurate value for J. Just one last question are the number of basis functions and the number of Molecular orbitals the same when you have hit this error?

**Comment by ivorever** [comment]
YES, I kept the oribits same when calculating by add int=nobasistransform to the route section. I am calculating the conjugated polymers which have good planarity so it is not suitable to remove some atoms

**Comment by JoshuaSBrown** [comment]
The issue with "#p" is now fixed:https://github.com/JoshuaSBrown/QC_Tools/pull/13
