### ISSUE TITLE
slight improvement and minor error correction

### ISSUE THREAD

**Issue by rdft4e** [JoshuaSBrown/QC_Tools#7]
Hi,
thank you for code it.

please check this little modification for qc_functions.cpp

line above ~309

`double J_eff = (J_ab-1/((double)2)*(e_b+e_a)*S_ab)/((double)(1-pow(S_ab,2)));
// J_eff = J_eff/((double)(1-pow(S_ab,2)));
  double sqrdiffepsiloneff = pow(e_a-e_b,2)/((double)(1-pow(S_ab,2)));

  cout << "J_ab = " << J_ab*hartreeToeV << " eV\n";
  cout << "e_a  = " << e_a*hartreeToeV << " eV\n";
  cout << "e_b  = " << e_b*hartreeToeV << " eV\n";
  cout << "S_ab = " << S_ab << " (-)\n";
  cout << "--------------------\n";
  cout << "J_eff   = " << J_eff*hartreeToeV << " eV\n";
  cout << "2*J_eff = " << 2*J_eff*hartreeToeV << " eV\n";
//  cout << "(e_a_eff - e_b_eff)^2  = " << sqrdiffepsiloneff*hartreeToeV << " (eV)^2\n";
  cout << "(e_a_eff - e_b_eff)    = " << sqrt(sqrdiffepsiloneff)*hartreeToeV << " eV\n";
  cout << "delta E = " << sqrt(sqrdiffepsiloneff+pow(2*J_eff,2))*hartreeToeV << " eV\n";
`
I have added the 2*Jeff, the difference of the effective energy site and delta E in the output.
There was a minor mistake swaping e_j between the string and the formula as here below: 
  cout << "e_a  = " << e_b*hartreeToeV << " eV\n";

Please, update only if you like. I do not know well to do a pull request in git, sorry.

Also, I have noted that the output for the LUMO - LUMO in wiki Tutorial 1 is said to be
J_eff -8.67354e-12 eV
but I got J_eff 0.142718 eV. Please check the command line code included in the wiki because
"-p_P GAUSSIANFILES/0/0_pair.pun" appears two times and really I think that you got really a HOMO - LUMO  Jeff.

Best wishes

**Comment by JoshuaSBrown** [comment]
Thanks @rdft4e I will try to add this in early next week.

**Comment by JoshuaSBrown** [comment]
@rdft4e for the code you have changed (not the documentation) you are making a suggestion to output more information or you are reporting a bug?

**Comment by JoshuaSBrown** [comment]
https://github.com/JoshuaSBrown/QC_Tools/pull/14/files Take a look here.

**Comment by rdft4e** [comment]
Hello,
I had suggested both. The minor correction that you just solved here https://github.com/JoshuaSBrown/QC_Tools/pull/14/files and also I modified the code to output more information (but it was not a bug of course)

Furthermore, I was playing a little with the program and checking it, then I realize that there is a mismatch between the output results for LUMO-LUMO case reported in the wiki and the output observed by using the program. There is more details in my first comment.

Finally, I would like to know if I use the output of this program for publication. How you like could be cited this code?

**Comment by JoshuaSBrown** [comment]
@rdft4e Thanks for the feed back, it was very helpful, I will wait to add more output just in case people already rely on the output in the current format.  Perhaps will add a flag to add the extra information you have suggested. I have added a citation flag so you can know how to cite it. Thanks for asking it is considerate of you. 

`./calc_J -cite`

**Comment by rdft4e** [comment]
I am ok with that. Please "close" the inquiry if you want. 
Cheers!
